name: Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore ./src
      - name: Build
        run: dotnet build ./src --no-restore

      - name: Test
        run: dotnet test ./src --filter "FullyQualifiedName!~WhenCompressMessage&FullyQualifiedName!~WhenSendJson" --no-build --verbosity normal
  push-nuget:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Restore dependencies
        run: dotnet restore ./src

      - name: Build
        run: dotnet build ./src --no-restore

      - name: Pack
        run: dotnet pack ./src/Serilog.Sinks.Graylog/Serilog.Sinks.Graylog.csproj --include-symbols --include-source -o /app/build

      - name: Push
        run: |
          cd /app/build
          dotnet nuget push ertelecom.Serilog.Sinks.Graylog.*.nupkg -k ${secrets.NUGET_API_KEY} -s https://api.nuget.org/v3/index.json
